from __future__ import annotations

import json
import re
from datetime import datetime, timezone
from pathlib import Path


OUT = Path(r"D:\python\artist_by_tag\var\wiki_drafts\MSLN")
NANOHA = "https://nanoha.fandom.com/wiki/"
COPYRIGHT = "mahou_shoujo_lyrical_nanoha_strikers_sound_stage_x"
INDEX = "List_of:Mahou_Shoujo_Lyrical_Nanoha_(franchise)"


# tag: (description, tagging/continuity note, Fandom page)
CHARACTERS = {
    "runessa_magnus": (
        "Runessa Magnus, commonly called Rune, is Teana Lanster's eighteen-year-old Executive Officer Assistant during the Mariage Incident. An orphan from war-torn Orusea, she is skilled in forensic investigation, research and marksmanship and uses the Device Silver Dagger. She is ultimately exposed as Tredia Graze's foster daughter and accomplice, having continued his plan after his death.",
        "Runessa is introduced in Sound Stage X and later appears only briefly in a Force flashback. No exact character tag was found in the local Gelbooru database; [[runessa_magnus]] is the proposed canonical tag.",
        "Runessa_Magnus",
    ),
    "ixveria": (
        "Ixveria is the ancient Hades, or Dark King, of Galea and the unwilling progenitor of the Mariage. Although she looks like a young girl, she has survived since the Ancient Belkan era in hibernation. Subaru finds and befriends her during the Mariage Incident; she later remains under the care of the Saint Church and returns in ViVid and ViVid Strike!.",
        "Use [[ixveria]], the canonical spelling established by later material. [[ixpellia]] is an older transliteration of the same character and should not be treated as a second person.",
        "Ixveria",
    ),
    "tredia_graze": (
        "Tredia Graze was an Orusean scientist and Runessa Magnus's foster father. After discovering Ixveria and the Mariage, he attempted to weaponize them against the administrated worlds. He died several years before the Mariage Incident, but Runessa continued his plan and impersonated him during the investigation.",
        "Tredia is heard and discussed in Sound Stage X but has no known official visual design. No exact character tag exists in the local database; [[tredia_graze]] is proposed for reference and future use.",
        "Tredia_Graze",
    ),
    "voltz_stan": (
        "Voltz Stan is a Ground Forces officer and Subaru Nakajima's superior during Sound Stage X. He helps coordinate the response to the Mariage Incident and the Marine Garden emergency.",
        "The local database contains [[voltz_stan]] as a character tag, with very few posts. He is a minor Sound Stage X character and should not be confused with similarly named characters from other copyrights.",
        "Voltz_Stan",
    ),
    "marriage_(nanoha)": (
        "The Mariage are artificial Ancient Belkan soldiers and the principal collective antagonists of Sound Stage X. Appearing as nearly identical masked women, they are produced from control cores generated by Ixveria and can transform their arms into weapons. Runessa Magnus deploys them in a series of murders and attacks during the Mariage Incident of 0078.",
        "The local character tag is [[marriage_(nanoha)]], although the official English name and reference page spell the group 'Mariage'. The unqualified [[marriage]] tag is unrelated, and the empty [[mariage]] character entry should not be used as a duplicate.",
        "Mariage",
    ),
}


def safe(tag: str) -> str:
    return re.sub(r"[^A-Za-z0-9_.()+-]+", "_", tag).strip("._") or "untitled"


def uploaded_names() -> set[str]:
    uploaded = OUT / "uploaded"
    return {path.name.casefold() for path in uploaded.rglob("*") if path.is_file()} if uploaded.is_dir() else set()


def save(tag: str, template: str, source: str) -> None:
    data = {"tag": tag, "template": template, "source": source, "updated_at": datetime.now(timezone.utc).isoformat()}
    (OUT / f"{safe(tag)}.json").write_text(json.dumps(data, ensure_ascii=False, indent=2) + "\n", encoding="utf-8")


def character_source(description: str, note: str, fandom_page: str) -> str:
    return (
        f"[b]Description:[/b]\n{description}\n\n[b]Tagging and continuity note:[/b]\n{note}\n\n"
        f"[b]Copyright:[/b]\n[[{COPYRIGHT}]]\n\n[b]See also:[/b]\n[[{COPYRIGHT}]]\n[[{INDEX}]]\n\n"
        f"[b]External sources:[/b]\n{NANOHA}{fandom_page}"
    )


def series_source() -> str:
    returning = [
        "teana_lanster", "subaru_nakajima", "ginga_nakajima", "erio_mondial", "caro_ru_lushe",
        "cinque_(nanoha)", "nove_(nanoha)", "dieci_(nanoha)", "wendi_(nanoha)", "sein_(nanoha)",
        "lutecia_alpine", "agito_(nanoha)", "genya_nakajima", "alto_krauetta", "vice_granscenic",
        "mariel_atenza", "mira_barret", "vivio",
    ]
    introduced = list(CHARACTERS)
    lines = [
        "StrikerSサウンドステージX",
        "",
        "StrikerS Sound Stage X, officially styled StrikerS Sound stage X and often shortened to SSX, is a two-disc audio drama written by Tsuzuki Masaki and released on October 29, 2008. It belongs to the primary continuity and takes place in year 0078, three years after the JS Incident depicted in Magical Girl Lyrical Nanoha StrikerS.",
        "",
        "The story focuses on the characters introduced in StrikerS rather than Nanoha, Fate and Hayate. Teana Lanster, assisted by Runessa Magnus, investigates a series of killings that draws the former Riot Force 6 forwards and the rehabilitated Numbers into conflict with the Mariage, artificial soldiers connected to the ancient Dark King Ixveria.",
        "",
        "[b]Characters introduced in Sound Stage X:[/b]",
        *[f"[[{tag}]]" for tag in introduced],
        "",
        "[b]Returning investigators and allies:[/b]",
        *[f"[[{tag}]]" for tag in returning],
        "",
        "[b]Referenced antagonists:[/b]",
        "[[jail_scaglietti]]",
        "[[quattro_(nanoha)]]",
        "[[tre_(nanoha)]]",
        "[[uno_(nanoha)]]",
        "",
        "[b]Follows:[/b]",
        "[[mahou_shoujo_lyrical_nanoha_strikers]]",
        "",
        "[b]Followed by:[/b]",
        "[[mahou_shoujo_lyrical_nanoha_vivid]]",
        "[[mahou_senki_lyrical_nanoha_force]]",
        "",
        "[b]See also:[/b]",
        f"[[{INDEX}]]",
        "[[numbers_(nanoha)]]",
        "",
        "[b]External sources:[/b]",
        NANOHA + "StrikerS_Sound_Stage_X",
        NANOHA + "Media",
        "https://en.wikipedia.org/wiki/Magical_Girl_Lyrical_Nanoha_Strikers",
    ]
    return "\n".join(lines)


def main() -> None:
    OUT.mkdir(parents=True, exist_ok=True)
    uploaded = uploaded_names()
    created = skipped = 0
    for tag, (description, note, fandom_page) in CHARACTERS.items():
        if f"{safe(tag)}.json".casefold() in uploaded:
            skipped += 1
            continue
        save(tag, "character", character_source(description, note, fandom_page))
        created += 1
    series_name = f"{safe(COPYRIGHT)}.json".casefold()
    if series_name not in uploaded:
        save(COPYRIGHT, "copyright", series_source())
        series_status = "created"
    else:
        series_status = "uploaded"
    print(f"Created {created} Sound Stage X character drafts, skipped {skipped} uploaded drafts; series page: {series_status}")


if __name__ == "__main__":
    main()
